import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';
import { RouterLink } from '@angular/router';
import { LogoComponent } from '../../shared/logo.component';

/**
 * Template legal documents. They are a starting point only: have them reviewed by a lawyer
 * licensed in every jurisdiction where you offer the service before going live.
 */
const DOCS: Record<string, { title: string; sections: { h: string; p: string[] }[] }> = {
  terms: {
    title: 'Terms & Conditions',
    sections: [
      { h: '1. The service', p: ['Y2 Markets ("we", "us") provides an online platform for fixed-time trades and contracts for difference (CFDs) on crypto-assets, currencies, commodities, stocks and indices, including OTC instruments priced by our own feed.'] },
      { h: '2. Eligibility', p: ['You must be at least 18 years old and legally allowed to use this type of service where you live. You are responsible for complying with your local laws.'] },
      { h: '3. Your account', p: ['You may hold one account. Keep your credentials secret and enable two-factor authentication. We may ask you to verify your identity (KYC) at any time and before withdrawals.'] },
      { h: '4. Pricing and execution', p: ['Trades open at the latest price recorded by our servers when your order is received; any price shown in your browser is indicative. Fixed-time trades settle at the last recorded price at or before expiry. Every tick used is stored and can be reviewed on request.', 'OTC instruments are generated by an independent pricing engine that has no access to client positions, trades or balances.'] },
      { h: '5. Deposits and withdrawals', p: ['Minimum deposit and withdrawal amounts are shown in the Finance section. Withdrawals are paid to a method in your own name, require a verified e-mail address, and are reviewed before payment.'] },
      { h: '6. Bonuses', p: ['Bonuses are optional and governed by the terms shown before you opt in. Bonus funds are kept separate from your deposits and you can cancel a bonus at any time.'] },
      { h: '7. Risk', p: ['Trading involves substantial risk and you can lose all of the money you invest. Read the Risk Disclosure before trading.'] },
      { h: '8. Changes and termination', p: ['We may update these terms with notice. You may close your account at any time; we may suspend accounts involved in fraud, abuse or breaches of these terms.'] },
    ],
  },
  privacy: {
    title: 'Privacy Policy',
    sections: [
      { h: 'What we collect', p: ['Account details (name, username, e-mail, phone), identity documents you upload for verification, transaction and trading records, and technical data such as IP address and device information.'] },
      { h: 'Why we collect it', p: ['To provide and secure the service, process payments, comply with anti-money-laundering obligations, prevent fraud and support you.'] },
      { h: 'Sharing', p: ['We share data only with payment providers (e.g. Safaricom M-Pesa), identity verification and hosting providers as needed to run the service, and with authorities where the law requires.'] },
      { h: 'Retention and your rights', p: ['We keep financial records for as long as the law requires. You can request access, correction or deletion of your data where applicable under the Kenya Data Protection Act 2019 and other laws, by contacting support@y2markets.site.'] },
      { h: 'Security', p: ['Passwords are hashed, sessions use short-lived tokens and optional two-factor authentication, and identity documents are stored outside the public web root.'] },
    ],
  },
  risk: {
    title: 'Risk Disclosure',
    sections: [
      { h: 'High risk', p: ['Fixed-time trades and CFDs are complex, high-risk products. Most retail traders lose money. Do not trade with money you cannot afford to lose.'] },
      { h: 'Fixed-time trades', p: ['If your forecast is wrong at expiry you lose your entire stake. If the price is unchanged at expiry your stake is refunded.'] },
      { h: 'CFDs and leverage', p: ['Leverage magnifies both gains and losses. Positions are closed automatically if losses approach the margin posted.'] },
      { h: 'OTC instruments', p: ['OTC prices come from our own feed rather than a public exchange. They are available 24/7, recorded tick-by-tick and never influenced by client positions.'] },
      { h: 'Signals and copy trading', p: ['Signals and copied trades are informational tools, not investment advice. Their historical accuracy is shown honestly and does not guarantee future results.'] },
    ],
  },
  aml: {
    title: 'AML & KYC Policy',
    sections: [
      { h: 'Our commitment', p: ['We do not tolerate money laundering or terrorist financing and cooperate with the relevant authorities.'] },
      { h: 'Verification', p: ['We may request a government ID, a selfie and proof of address. Withdrawals are paid only to payment methods in the account holder\'s name.'] },
      { h: 'Monitoring', p: ['Transactions are monitored and unusual activity may be reviewed, delayed or reported as required by law.'] },
    ],
  },
};

@Component({
  selector: 'app-legal',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [RouterLink, LogoComponent],
  template: `
    <header><a routerLink="/"><app-logo [size]="40" /></a></header>
    <main class="card anim-rise">
      @if (page(); as d) {
        <h1>{{ d.title }}</h1>
        <p class="muted">Last updated: 1 September 2026</p>
        @for (s of d.sections; track s.h) {
          <h3>{{ s.h }}</h3>
          @for (p of s.p; track $index) {
            <p>{{ p }}</p>
          }
        }
      }
      <nav>
        <a routerLink="/legal/terms">Terms</a><a routerLink="/legal/privacy">Privacy</a><a routerLink="/legal/risk">Risk Disclosure</a><a routerLink="/legal/aml">AML Policy</a>
      </nav>
    </main>
  `,
  styles: [
    `:host{display:block;min-height:100vh;background:linear-gradient(180deg,#0b0f18,var(--bg));padding:24px 16px 60px}
     header{max-width:860px;margin:0 auto 24px}
     main{max-width:860px;margin:0 auto;padding:40px;line-height:1.7}
     h1{font-size:36px;margin-bottom:4px} h3{margin:28px 0 6px;font-size:18px} p{color:#c5cedc}
     nav{display:flex;gap:18px;flex-wrap:wrap;margin-top:40px;padding-top:20px;border-top:1px solid var(--border)}
     @media(max-width:640px){main{padding:22px}}`,
  ],
})
export class LegalComponent {
  readonly doc = input<string>('terms');
  protected page = computed(() => DOCS[this.doc()] ?? DOCS['terms']);
}
